### ISSUE TITLE
Could you share the pretrained model for imagenet?

### ISSUE THREAD

**Issue by xztema0207** [bayesgroup/pytorch-ensembles#3]
I think there are no pretrained model to test the performance .
Could you share the pretrained model for imagenet and cifar100?
(ex. in source, fnames='~/megares/ImageNet-ResNet50-cn-025--1564562952-1.pth.tar'

**Comment by senya-ashukha** [comment]
Hi, 

Thank you for reaching out! 

I've made the weights of deep ensembles available for [ImageNet](https://yadi.sk/d/rdk6ylF5mK8ptw?w=1). A link for CIFAR will appear at readme a bit latter.  All the weights take a lot of space ~ 1TB and will be hard to store and download.  But if you strongly need some specific models let us know.

Arsenii

**Comment by xztema0207** [comment]
Thanks for your sharing!

I downloaded files for imagenet. 
but, I can't distinquish the content of files in zip file. (ex. what is for BayesResnet50? What is for fge? What is for sse?
Could you share the pretrained files respectively for BayesResnet50, BayesResneXt101, fge, swa, swag, sse?

I hope to test each algorithm with imagenet.

**Comment by senya-ashukha** [comment]
I think the further discussion is available at https://github.com/bayesgroup/pytorch-ensembles/issues/4
