### ISSUE TITLE
Could you share the pretrained files respectively for BayesResnet50, BayesResneXt101, fge, swa, swag, sse?

### ISSUE THREAD

**Issue by xztema0207** [bayesgroup/pytorch-ensembles#4]
Thanks for your sharing!

I downloaded files for imagenet.
but, I can't distinquish the content of files in zip file. (ex. what is for BayesResnet50? What is for fge? What is for sse?
Could you share the pretrained files respectively for BayesResnet50, BayesResneXt101, fge, swa, swag, sse?

I hope to test each algorithm with imagenet.

**Comment by senya-ashukha** [comment]
Hi,

We the weights that are already shared are **only** for Deep Ensembles. So there are no files for vi/fge/sse at the moment. 
I'm sorry, but we didn't have experiments with BayesResneXt101 and swa in the paper :)

We can release weights for vi (BayesResnet50), fge, sse on **ImageNet** but it may take several days. Does it sound good?

**Comment by senya-ashukha** [comment]
Check out the following models https://yadi.sk/d/qwwESfJkkO48Bw?w=1
